sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
sh: pause: command not found
